### ISSUE TITLE
1822 direkt bank

### ISSUE THREAD

**Issue by localguru** [msc01/soacsv2mt940#4]
Hi,

is it possible to convert a .csv export from 1822direct bank to MT940?

Ciao!

**Comment by msc01** [comment]
Shouldn't be a big deal...could you provide an example file and / or the description e.g. header of the according .csv export from 1822direct bank?

**Comment by localguru** [comment]
Thanks for your time. Here we go ...

[umsaetze-17.04.2019_18_56.csv.txt](https://github.com/msc01/soacsv2mt940/files/3091764/umsaetze-17.04.2019_18_56.csv.txt)

**Comment by Heart1010** [comment]
I just saw this issue... 

@msc01 if you want I can provide you with a "pseudo" csv file which every Raiffeisenbank/Volksbank/Genossenschaftsbank customer in germany gets when they click the "csv export" icon in the eBanking interface. This one is really "a bit different" than a usual csv file 😟

![Umsaetze_DE637316000000012345678_2019 04 18_x](https://user-images.githubusercontent.com/1481680/56357639-8eeb5e80-61dc-11e9-90c9-f56255072f79.png)


[Umsaetze_DE637316000000012345678_2019.04.18_x.csv.txt](https://github.com/msc01/soacsv2mt940/files/3094136/Umsaetze_DE637316000000012345678_2019.04.18_x.csv.txt)

**Comment by msc01** [comment]
@Heart1010 I think this is worth a new issue (see #5) esp. as the Raiffeisenbank/Volksbank/Genossenschaftsbank format really looks different than other export formats...

**Comment by msc01** [comment]
@localguru Had a quick glance at the example you provided for 1822 direkt banks. As stated initially it is close to the already implemented format of Commerzbank, hence implementation shouldn't be a big deal.

I think I will introduce an additional command line parameter to switch between different bank / formats. 

A new version will take some days due to the good weather ;-)

**Comment by localguru** [comment]
@msc01 Thank you!

**Comment by localguru** [comment]
@msc01 I played a little bit with Hibiscus, so we can compare the output then.

**Comment by msc01** [comment]
I've just committed a new version which supports converting .csv export files from 1822direkt Bank with the new command line parameter `-f  --format 1822direkt`

It's a very simple implementation which is in need of further refactoring esp. with issue #5 / other .csv file formats in mind.

Testing is primarily based on the given example file with only 1 record hence I'm sure there will be issues when real data is processed - just let me know and / or please provide more test data.
