### ISSUE TITLE
Raiffeisenbank/Volksbank/Genossenschaftsbank

### ISSUE THREAD

**Issue by msc01** [msc01/soacsv2mt940#5]
I just saw this issue... 

@msc01 if you want I can provide you with a "pseudo" csv file which every Raiffeisenbank/Volksbank/Genossenschaftsbank customer in germany gets when they click the "csv export" icon in the eBanking interface. This one is really "a bit different" than a usual csv file 😟

![Umsaetze_DE637316000000012345678_2019 04 18_x](https://user-images.githubusercontent.com/1481680/56357639-8eeb5e80-61dc-11e9-90c9-f56255072f79.png)

[Umsaetze_DE637316000000012345678_2019.04.18_x.csv.txt](https://github.com/msc01/soacsv2mt940/files/3094136/Umsaetze_DE637316000000012345678_2019.04.18_x.csv.txt)

_Originally posted by @Heart1010 in https://github.com/msc01/soacsv2mt940/issues/4#issuecomment-484461412_

**Comment by msc01** [comment]
This will definitely take more time...more data / test files are more than welcome!

**Comment by msc01** [comment]
Done with this [commit](https://github.com/msc01/soacsv2mt940/commit/38c59f1a375bb406e9041c31413d630be0ae113a) / v0.2.2

**Comment by Heart1010** [comment]
Thanks! 👍 

A general info about all the Raiffeisen- und Volksbanken / Genossenschaftsbanken out there in germany - they will switch their banking system to a new plattform until the end of the year. With this new plattform the csv export is still more or less in this "strange" format you know - but alongside the csv export their will be now a MT940-export feature built in for all clients.
